//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sis.Ges.Doc.Frontend.UserService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.UserServiceSoap")]
    public interface UserServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PasswordEncrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PasswordEncrypt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PasswordEncrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PasswordEncryptAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCategoria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarCategoria(string nombreCategoria, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertarCategoriaAsync(string nombreCategoria, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCategorias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCategorias", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCategoriaPorId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerCategoriaPorId(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCategoriaPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCategoriaPorIdAsync(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCategoria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizarCategoria(int idCategoria, string nombreCategoria, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ActualizarCategoriaAsync(int idCategoria, string nombreCategoria, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCategoria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarCategoria(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EliminarCategoriaAsync(int idCategoria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : Sis.Ges.Doc.Frontend.UserService.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<Sis.Ges.Doc.Frontend.UserService.UserServiceSoap>, Sis.Ges.Doc.Frontend.UserService.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PasswordEncrypt() {
            return base.Channel.PasswordEncrypt();
        }
        
        public System.Threading.Tasks.Task<string> PasswordEncryptAsync() {
            return base.Channel.PasswordEncryptAsync();
        }
        
        public string InsertarCategoria(string nombreCategoria, string descripcion) {
            return base.Channel.InsertarCategoria(nombreCategoria, descripcion);
        }
        
        public System.Threading.Tasks.Task<string> InsertarCategoriaAsync(string nombreCategoria, string descripcion) {
            return base.Channel.InsertarCategoriaAsync(nombreCategoria, descripcion);
        }
        
        public System.Data.DataSet ObtenerCategorias() {
            return base.Channel.ObtenerCategorias();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCategoriasAsync() {
            return base.Channel.ObtenerCategoriasAsync();
        }
        
        public System.Data.DataSet ObtenerCategoriaPorId(int idCategoria) {
            return base.Channel.ObtenerCategoriaPorId(idCategoria);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCategoriaPorIdAsync(int idCategoria) {
            return base.Channel.ObtenerCategoriaPorIdAsync(idCategoria);
        }
        
        public string ActualizarCategoria(int idCategoria, string nombreCategoria, string descripcion) {
            return base.Channel.ActualizarCategoria(idCategoria, nombreCategoria, descripcion);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarCategoriaAsync(int idCategoria, string nombreCategoria, string descripcion) {
            return base.Channel.ActualizarCategoriaAsync(idCategoria, nombreCategoria, descripcion);
        }
        
        public string EliminarCategoria(int idCategoria) {
            return base.Channel.EliminarCategoria(idCategoria);
        }
        
        public System.Threading.Tasks.Task<string> EliminarCategoriaAsync(int idCategoria) {
            return base.Channel.EliminarCategoriaAsync(idCategoria);
        }
    }
}
