//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sis.Ges.Doc.Frontend.UserService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.UserServiceSoap")]
    public interface UserServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PasswordEncrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PasswordEncrypt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PasswordEncrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PasswordEncryptAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarUsuario(string nombreCompleto, string correo, string usuario, string passwordHash, int idDepartamento, string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertarUsuarioAsync(string nombreCompleto, string correo, string usuario, string passwordHash, int idDepartamento, string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuarioPorId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerUsuarioPorId(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuarioPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerUsuarioPorIdAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizarUsuario(int idUsuario, string nombreCompleto, string correo, string usuario, string passwordHash, int idDepartamento, string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ActualizarUsuarioAsync(int idUsuario, string nombreCompleto, string correo, string usuario, string passwordHash, int idDepartamento, string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EliminarUsuarioAsync(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : Sis.Ges.Doc.Frontend.UserService.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<Sis.Ges.Doc.Frontend.UserService.UserServiceSoap>, Sis.Ges.Doc.Frontend.UserService.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PasswordEncrypt() {
            return base.Channel.PasswordEncrypt();
        }
        
        public System.Threading.Tasks.Task<string> PasswordEncryptAsync() {
            return base.Channel.PasswordEncryptAsync();
        }
        
        public string InsertarUsuario(string nombreCompleto, string correo, string usuario, string passwordHash, int idDepartamento, string rol) {
            return base.Channel.InsertarUsuario(nombreCompleto, correo, usuario, passwordHash, idDepartamento, rol);
        }
        
        public System.Threading.Tasks.Task<string> InsertarUsuarioAsync(string nombreCompleto, string correo, string usuario, string passwordHash, int idDepartamento, string rol) {
            return base.Channel.InsertarUsuarioAsync(nombreCompleto, correo, usuario, passwordHash, idDepartamento, rol);
        }
        
        public System.Data.DataSet ObtenerUsuarios() {
            return base.Channel.ObtenerUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerUsuariosAsync() {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public System.Data.DataSet ObtenerUsuarioPorId(int idUsuario) {
            return base.Channel.ObtenerUsuarioPorId(idUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerUsuarioPorIdAsync(int idUsuario) {
            return base.Channel.ObtenerUsuarioPorIdAsync(idUsuario);
        }
        
        public string ActualizarUsuario(int idUsuario, string nombreCompleto, string correo, string usuario, string passwordHash, int idDepartamento, string rol) {
            return base.Channel.ActualizarUsuario(idUsuario, nombreCompleto, correo, usuario, passwordHash, idDepartamento, rol);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarUsuarioAsync(int idUsuario, string nombreCompleto, string correo, string usuario, string passwordHash, int idDepartamento, string rol) {
            return base.Channel.ActualizarUsuarioAsync(idUsuario, nombreCompleto, correo, usuario, passwordHash, idDepartamento, rol);
        }
        
        public string EliminarUsuario(int idUsuario) {
            return base.Channel.EliminarUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<string> EliminarUsuarioAsync(int idUsuario) {
            return base.Channel.EliminarUsuarioAsync(idUsuario);
        }
    }
}
