//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sis.Ges.Doc.Frontend.BitacoraService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BitacoraService.BitacoraServiceSoap")]
    public interface BitacoraServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserIPAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUserIPAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserIPAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUserIPAddressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerBitacora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerBitacora();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerBitacora", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerBitacoraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerBitacoraPorId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerBitacoraPorId(int idBitacora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerBitacoraPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerBitacoraPorIdAsync(int idBitacora);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BitacoraServiceSoapChannel : Sis.Ges.Doc.Frontend.BitacoraService.BitacoraServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BitacoraServiceSoapClient : System.ServiceModel.ClientBase<Sis.Ges.Doc.Frontend.BitacoraService.BitacoraServiceSoap>, Sis.Ges.Doc.Frontend.BitacoraService.BitacoraServiceSoap {
        
        public BitacoraServiceSoapClient() {
        }
        
        public BitacoraServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BitacoraServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BitacoraServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BitacoraServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUserIPAddress() {
            return base.Channel.GetUserIPAddress();
        }
        
        public System.Threading.Tasks.Task<string> GetUserIPAddressAsync() {
            return base.Channel.GetUserIPAddressAsync();
        }
        
        public System.Data.DataSet ObtenerBitacora() {
            return base.Channel.ObtenerBitacora();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerBitacoraAsync() {
            return base.Channel.ObtenerBitacoraAsync();
        }
        
        public System.Data.DataSet ObtenerBitacoraPorId(int idBitacora) {
            return base.Channel.ObtenerBitacoraPorId(idBitacora);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerBitacoraPorIdAsync(int idBitacora) {
            return base.Channel.ObtenerBitacoraPorIdAsync(idBitacora);
        }
    }
}
