//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sis.Ges.Doc.Frontend.DocService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocService.DocServiceSoap")]
    public interface DocServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarDocumento(string filePath, string nombreDocumento, string descripcion, int idCategoria, System.DateTime fechaDoc, int idUsuarioResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertarDocumentoAsync(string filePath, string nombreDocumento, string descripcion, int idCategoria, System.DateTime fechaDoc, int idUsuarioResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDocumentos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerDocumentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDocumentos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerDocumentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDocumentoPorId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerDocumentoPorId(int idDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDocumentoPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerDocumentoPorIdAsync(int idDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizarDocumento(int idDocumento, string nombreDocumento, string descripcion, int idCategoria, System.DateTime fechaRegistro, int idUsuarioResponsable, int idUsuarioModificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ActualizarDocumentoAsync(int idDocumento, string nombreDocumento, string descripcion, int idCategoria, System.DateTime fechaRegistro, int idUsuarioResponsable, int idUsuarioModificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarDocumento(int idDocumento, int idUsuarioModificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EliminarDocumentoAsync(int idDocumento, int idUsuarioModificacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocServiceSoapChannel : Sis.Ges.Doc.Frontend.DocService.DocServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocServiceSoapClient : System.ServiceModel.ClientBase<Sis.Ges.Doc.Frontend.DocService.DocServiceSoap>, Sis.Ges.Doc.Frontend.DocService.DocServiceSoap {
        
        public DocServiceSoapClient() {
        }
        
        public DocServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertarDocumento(string filePath, string nombreDocumento, string descripcion, int idCategoria, System.DateTime fechaDoc, int idUsuarioResponsable) {
            return base.Channel.InsertarDocumento(filePath, nombreDocumento, descripcion, idCategoria, fechaDoc, idUsuarioResponsable);
        }
        
        public System.Threading.Tasks.Task<string> InsertarDocumentoAsync(string filePath, string nombreDocumento, string descripcion, int idCategoria, System.DateTime fechaDoc, int idUsuarioResponsable) {
            return base.Channel.InsertarDocumentoAsync(filePath, nombreDocumento, descripcion, idCategoria, fechaDoc, idUsuarioResponsable);
        }
        
        public System.Data.DataSet ObtenerDocumentos() {
            return base.Channel.ObtenerDocumentos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerDocumentosAsync() {
            return base.Channel.ObtenerDocumentosAsync();
        }
        
        public System.Data.DataSet ObtenerDocumentoPorId(int idDocumento) {
            return base.Channel.ObtenerDocumentoPorId(idDocumento);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerDocumentoPorIdAsync(int idDocumento) {
            return base.Channel.ObtenerDocumentoPorIdAsync(idDocumento);
        }
        
        public string ActualizarDocumento(int idDocumento, string nombreDocumento, string descripcion, int idCategoria, System.DateTime fechaRegistro, int idUsuarioResponsable, int idUsuarioModificacion) {
            return base.Channel.ActualizarDocumento(idDocumento, nombreDocumento, descripcion, idCategoria, fechaRegistro, idUsuarioResponsable, idUsuarioModificacion);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarDocumentoAsync(int idDocumento, string nombreDocumento, string descripcion, int idCategoria, System.DateTime fechaRegistro, int idUsuarioResponsable, int idUsuarioModificacion) {
            return base.Channel.ActualizarDocumentoAsync(idDocumento, nombreDocumento, descripcion, idCategoria, fechaRegistro, idUsuarioResponsable, idUsuarioModificacion);
        }
        
        public string EliminarDocumento(int idDocumento, int idUsuarioModificacion) {
            return base.Channel.EliminarDocumento(idDocumento, idUsuarioModificacion);
        }
        
        public System.Threading.Tasks.Task<string> EliminarDocumentoAsync(int idDocumento, int idUsuarioModificacion) {
            return base.Channel.EliminarDocumentoAsync(idDocumento, idUsuarioModificacion);
        }
    }
}
